---
name: "run-unittests-on-build"
description: "Runs unit tests on Docker image build"

inputs:
  image_tag:
    required: true
    type: string
    description: "Tag of the image"
  timeout_seconds:
    required: true
    type: integer
    description: "Timeout for the server to startup"
    default: "300"

runs:
  using: "composite"
  steps:
    - name: Get Runner Info
      shell: bash
      run: |
        id
        pwd
        git --version
        docker version
        free -m
        cat /proc/cpuinfo | grep "model name"
        echo "Repository value of TIMEOUT_SECONDS is: ${{ inputs.timeout_seconds }}"
        echo "This should be set on develop or main branch!"

    - name: Run server
      shell: bash
      run: |
        docker run -d \
        --name palworld-dedicated-server \
        -p 8211:8211/udp \
        -p 8212:8212/tcp \
        -p 25575:25575/tcp \
        -e PUID=7351 \
        -e PGID=2431 \
        -e ADMIN_PASSWORD=123 \
        -e SERVER_PASSWORD=456 \
        -e SERVER_SETTINGS_MODE=auto \
        -v ./game:/palworld/ \
        --restart unless-stopped \
        --stop-timeout 30 \
        jammsen/palworld-dedicated-server:${{ inputs.image_tag }}

    - name: Wait for server to start
      shell: bash
      run: |
        START_TIME=$(date +%s)
        TIMEOUT_SECONDS=${{ inputs.timeout_seconds || '300' }}
        echo "TIMEOUT_SECONDS: $TIMEOUT_SECONDS"

        # Set the timezone to Germany (Central European Time)
        export TZ=Europe/Berlin
        
        # Source color functions
        source ./includes/colors.sh

        # Track last log position to avoid duplicate output
        LAST_LOG_LINES=0

        while ! docker logs palworld-dedicated-server 2>&1 | grep -q "Setting breakpad minidump AppID"; do
          CURRENT_TIME=$(date +%s)
          ELAPSED_TIME=$((CURRENT_TIME - START_TIME))

          if [ $ELAPSED_TIME -gt $TIMEOUT_SECONDS ]; then
            echo "Timeout reached. Server failed to start within $TIMEOUT_SECONDS seconds."
            es "*****Final Container LOGS*****"
            docker logs palworld-dedicated-server
            exit 1
          fi

          # Show current status with warning color
          ew ">>> $(date '+%H:%M:%S') - Waiting for server to start... (${ELAPSED_TIME}s elapsed)"            
          # Get current log lines count and show new logs if any
          CURRENT_LOG_LINES=$(docker logs palworld-dedicated-server 2>&1 | wc -l)
          if [ $CURRENT_LOG_LINES -gt $LAST_LOG_LINES ]; then
            es ">>> Recent container logs"
            es "╭─────────────────────────────────────────────────────────────────────────────────────────────────────╮"
            docker logs palworld-dedicated-server 2>&1 | tail -n +$((LAST_LOG_LINES + 1)) | head -n $((CURRENT_LOG_LINES - LAST_LOG_LINES))
            es "╰─────────────────────────────────────────────────────────────────────────────────────────────────────╯"
            LAST_LOG_LINES=$CURRENT_LOG_LINES
          fi
          
          echo "---"
          sleep 5
        done

        echo "Server successfully started in $ELAPSED_TIME seconds"
        es "*****Final Container LOGS*****"
        docker logs palworld-dedicated-server


    - name: Test if port 8766, 27015 and 27016 are listening
      shell: bash
      run: |
        nc -z -u -v 127.0.0.1 8211 || exit 2
        nc -z -v 127.0.0.1 8212 || exit 3
        nc -z -v 127.0.0.1 25575 || exit 4

    - name: Stop server
      shell: bash
      if: always()
      run: |
        docker stop palworld-dedicated-server
        docker rm palworld-dedicated-server
